channels:
- conda-forge

dependencies:
# Items required for basic level functionality
- gh-scoped-creds==4.1
- git==2.47.0
- jupyter-resource-usage==1.1.0
- jupyter_server==2.14.2
- jupyterhub==5.2.1
- jupyterlab==4.2.5
- jupyterlab-git==0.50.1
- jupytext==1.16.4
- nbgitpuller==1.2.1
- notebook==7.2.2
- python==3.11.*

# Other items
- ipywidgets==8.1.2
- nbclassic==1.1.0
- jupyter-server-proxy==4.4.0
- jupyter-vscode-proxy==0.6
- code-server==4.23.1
- syncthing==1.27.12
- websockify==0.12.0
- appmode=1.0.0
- jupyter-syncthing-proxy==1.0.3
# https://github.com/berkeley-dsep-infra/datahub/issues/2535
# gcc, gdb, etc are newer in conda-forge than in apt, esp with Ubuntu focal
- c-compiler==1.8.0
- cxx-compiler==1.8.0
- fortran-compiler==1.8.0
- gdb==15.1
- libopenblas=0.3.28
- liblapack=3.9.0
- armadillo==14.0.3
- gperf==3.1
# CS 16A
# From https://github.com/berkeley-dsep-infra/datahub/issues/1363#issuecomment-598916469
- numpy==1.26.*
- matplotlib==3.8.*
- sympy==1.12
# For EECS127/227a
# See https://github.com/berkeley-dsep-infra/datahub/issues/1631
- cvxpy==1.4.3
# See https://github.com/berkeley-dsep-infra/datahub/issues/1936
- scikit-learn=1.4.*
# From https://github.com/berkeley-dsep-infra/datahub/issues/1505
- Pillow==10.4.0
# For ELENG 120 https://github.com/berkeley-dsep-infra/datahub/issues/3566
- scipy==1.14.1
- gcc==13.3.0
# https://github.com/berkeley-dsep-infra/datahub/issues/4460
- sk-video==1.1.10
- ffmpeg==5.1.2
# https://github.com/berkeley-dsep-infra/datahub/issues/4708
- datascience==0.17.6
# https://jira-secure.berkeley.edu/browse/DH-456
- otter-grader==6.1.0

- pip==24.2
- pip:
# From https://github.com/berkeley-dsep-infra/datahub/issues/1639
  - opencv-python==4.9.0.80
  - PyQt5==5.15.11
# From https://github.com/berkeley-dsep-infra/datahub/issues/1363#issuecomment-598916469
  - lcapy==0.96
# make webpdf export work DH-326
  - nbconvert[webpdf]==7.16.4
# For desktop environment
  - jupyter-desktop-server==0.1.3
  - jupyter-archive==3.4.0
  - rise==5.7.1
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - git-credential-helpers==0.2
  - jupyter-tree-download==1.0.1
